[package]
name = "asm-run"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asm-compiler = { path = "../asm-compiler" }
virtual-machine = { path = "../virtual-machine" }
